### ISSUE TITLE
How to custom controls

### ISSUE THREAD

**Issue by mansai** [NorthwoodsSoftware/GoDiagram#5]
custom GraphObject Textbox Checkbox TabControl Groupbox add to diagram
![image](https://github.com/NorthwoodsSoftware/GoDiagram/assets/3213405/8748d51f-e8e0-44f4-8ddb-d267790e833f)

**Comment by jonchardy** [comment]
This seems like something that should be implemented outside of GoDiagram. You can have a containing panel that holds both a DiagramControl and whatever custom controls you want, and position your controls relative to the diagram if needed.

GoDiagram doesn't support custom controls as nodes since it uses a SkiaSharp canvas to render and is a "black box" for performance reasons.

Certain controls like tooltips, context menus, and text editors can be shown/hidden via the [IShowHidable](https://godiagram.com/winforms/latest/api/symbols/Northwoods.Go.IShowHidable.html) interface.

**Comment by mansai** [comment]
Avalonia.Controls also uses SkiaSharp

![image](https://github.com/NorthwoodsSoftware/GoDiagram/assets/3213405/9809b407-40ce-4887-888c-3adf03e9369e)

**Comment by jonchardy** [comment]
Yes, Avalonia and WinForms are both using SkiaSharp for rendering. In both cases, we are using a canvas, which cannot draw arbitrary controls to its surface.
