### ISSUE TITLE
Blazor wasm?

### ISSUE THREAD

**Issue by dazinator** [NorthwoodsSoftware/GoDiagram#8]
Would it be possible to use this in a blazor wasm application?

**Comment by jonchardy** [comment]
We do have an example project using GoJS, our Javascript diagramming library, within Blazor:
https://github.com/NorthwoodsSoftware/GoJS-Alongside-Blazor
Specifically,
https://github.com/NorthwoodsSoftware/GoJS-Alongside-Blazor/blob/master/GoJSBlazor/wwwroot/js/gojs-scripts.js

GoJS saves/loads models using JSON.

We did explore writing a Blazor (C#) GoDiagram library, but found the performance unsuitable, since Blazor interop with an HTML canvas is slow. We may revisit that at some point, but currently recommend GoJS.
